name: Simple
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  native:
    name: "Simple: GHC ${{ matrix.ghc }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        ghc: ['8.10','9.0','9.2','9.4','9.6']
      fail-fast: false
    timeout-minutes:
      60
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Haskell
        id: setup-haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest

      - name: Get precise GHC version
        shell: bash
        run: echo "GHC_VERSION=$(ghc --numeric-version)" >> "${GITHUB_ENV}"

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ env.GHC_VERSION }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.GHC_VERSION }}-

      - name: Build
        run: cabal build all --enable-tests

      - name: Test
        run: cabal test all --enable-tests --test-show-details=direct
